import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import About from "../sections/About";
import Explore from "../sections/Explore";
import Feedback from "../sections/Feedback";
import GetStarted from "../sections/GetStarted";
import Hero from "../sections/Hero";
import Insights from "../sections/Insights";
import WhatsNew from "../sections/WhatsNew";
import World from "../sections/World";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="bg-primary-black overflow-hidden">
					<Navbar />
					{/* <Hero />

					<div className="relative">
						<About />
					</div>
					<div className="gradient-03 z-0" />
					<Explore />
					<div className="relative">
						<GetStarted />
						<div className="gradient-03 z-0" />
						<WhatsNew />
					</div>
					<World />
					<div className="relative">
						<Insights />
						<div className="gradient-03 z-0" />
						<Feedback />
					</div>
					<Footer /> */}
				</div>
			</main>
		</>
	);
}
